# Generated by Django 4.0.5 on 2022-06-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_pf', models.IntegerField(max_length=11)),
                ('rg_pf', models.IntegerField(max_length=7)),
                ('nome_pf', models.CharField(max_length=30)),
                ('sexo_pf', models.CharField(max_length=20)),
                ('dataNasc_pf', models.DateField(max_length=10)),
            ],
        ),
    ]
