# Generated by Django 4.0.5 on 2022-06-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_fun', models.IntegerField(max_length=11)),
                ('rg_fun', models.IntegerField(max_length=7)),
                ('nome_fun', models.CharField(max_length=30)),
                ('sexo_fun', models.CharField(max_length=5)),
                ('data_nasc', models.DateField(max_length=11)),
                ('carteira_fu', models.IntegerField(max_length=11)),
                ('salario_fun', models.IntegerField(max_length=11)),
                ('pis_fun', models.IntegerField(max_length=11)),
            ],
        ),
    ]
