# Generated by Django 4.0.5 on 2022-06-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_cliente', models.CharField(max_length=50)),
                ('dados_corretor', models.CharField(max_length=50)),
                ('descricao_imo', models.CharField(max_length=50)),
                ('valorCont', models.CharField(max_length=50)),
                ('doc', models.CharField(max_length=50)),
                ('clausula', models.CharField(max_length=50)),
            ],
        ),
    ]
